import {test,expect,settle} from './fixtures.js'

const state=page=>page.evaluate(()=>Object.fromEntries(new URLSearchParams(location.search)))
const search=page=>page.locator('input[type="search"]:visible').first()
test('Archive URL state survives refresh, detail, history, locale change and re-entry',async({page,path,locale})=>{
  await page.goto(path('/archive/characters'))
  await settle(page)
  await expect.poll(()=>state(page)).toEqual({faction:'qin'})
  await page.locator('.fac-item').nth(1).click()
  await expect.poll(()=>state(page)).toEqual({faction:'zhao'})
  await page.reload()
  await expect(page.locator('.fac-active')).toHaveCount(1)
  await expect.poll(()=>state(page)).toEqual({faction:'zhao'})
  await expect(page.locator('.banner-card[data-detail-id="riboku"]')).toBeVisible()
  await search(page).fill('Moubu')
  await expect(page.locator('.fac-active')).toHaveCount(0)
  const card=page.locator('.banner-card[data-detail-id="moubu"]')
  await expect(card).toBeVisible() // Text searches the entire roster, despite Zhao context.
  await expect(card).toHaveAttribute('href',path('/archive/characters/moubu')+'?faction=zhao&q=Moubu')
  await card.click()
  await expect(page.locator('.detail-name')).toBeFocused()
  await page.locator('.detail-close').click()
  await expect(search(page)).toHaveValue('Moubu')
  await expect(card).toBeFocused()
  await page.goBack()
  await expect(page.locator('.detail-name')).toBeVisible()
  await page.goBack()
  await expect(search(page)).toHaveValue('Moubu')
  await page.goBack()
  await expect(search(page)).toHaveValue('')
  await expect.poll(()=>state(page)).toEqual({faction:'qin'})
  await page.goForward()
  await expect(search(page)).toHaveValue('Moubu')
  await page.reload()
  await expect(search(page)).toHaveValue('Moubu')
  const next=locale==='fr'?'en':'fr'
  await page.locator('.locale-switcher select').selectOption(next)
  await expect(page.locator('html')).toHaveAttribute('lang',next)
  await expect(search(page)).toHaveValue('Moubu')
  await expect.poll(()=>state(page)).toEqual({faction:'zhao',q:'Moubu'})
  // Follow real navigation out through Guide and back through the Archive hub.
  await page.locator('.bottom-nav a[href$="/guide"]').click()
  await page.locator('.bottom-nav a[href$="/archive"]').click()
  await page.locator('.archive-hub a[href$="/archive/characters"]').click()
  await expect(search(page)).toHaveValue('Moubu')
  await expect.poll(()=>state(page)).toEqual({faction:'zhao',q:'Moubu'})
  await page.locator('.fac-item').nth(1).click()
  await expect(search(page)).toHaveValue('') // Faction selection still clears text.
  await expect.poll(()=>state(page)).toEqual({faction:'zhao'})
})

test('explicit and malformed URLs take precedence over the per-tab return bookmark',async({page,path})=>{
  await page.goto(path('/archive/characters')+'?faction=zhao&q=Moubu')
  await expect(search(page)).toHaveValue('Moubu')
  await page.goto(path('/archive/characters')+'?faction=unknown&q=%00&q=Moubu')
  await expect(search(page)).toHaveValue('')
  await expect(page.locator('.fac-item').first()).toHaveClass(/fac-active/)
  await expect(page.locator('.banner-card')).toHaveCount(100)
  await page.goto(path('/archive/characters/renpa'))
  await expect(page.locator('.detail-name')).toBeVisible()
  await page.locator('.detail-close').click()
  await expect.poll(()=>state(page)).toEqual({faction:'wei'})
  await expect(page.locator('.banner-card[data-detail-id="renpa"]')).toBeFocused()
})
