import { test, expect, settle, instrumentStorage, saved, storage } from './fixtures.js'

for (const width of [320, 390, 820, 1440]) test(`${width}px CW6 reveals visible artwork without changing cards or saved ownership`, async ({ page, path }) => {
  await page.setViewportSize({ width, height: 844 })
  await instrumentStorage(page, saved)
  await page.goto(path('/archive/cw6-scene-cards'))
  await settle(page)
  const cards = page.locator('.cw6-card')
  const last = cards.last()
  const lastArt = last.locator('.cw6-card-art > img')
  const lastOwner = last.locator('.cw6-card-owner-ico')
  await expect(lastArt).not.toHaveAttribute('src')
  await expect(lastOwner).not.toHaveAttribute('src')
  const before = await last.locator('.cw6-card-art').boundingBox()
  expect(before.width).toBeGreaterThan(50)
  expect(Math.abs(before.width - before.height)).toBeLessThan(1)
  const initialSources = await cards.locator('img[src]').count()
  expect(initialSources).toBeLessThan((await cards.count()) * 2)
  await last.scrollIntoViewIfNeeded()
  await expect(lastArt).toHaveAttribute('src', /.+/)
  await expect(lastOwner).toHaveAttribute('src', /.+/)
  await expect(lastArt).toHaveClass(/is-loaded/)
  await expect.poll(() => lastArt.evaluate(image => image.complete && image.naturalWidth > 0)).toBe(true)
  const after = await last.locator('.cw6-card-art').boundingBox()
  expect(after.width).toBe(before.width)
  expect(after.height).toBe(before.height)
  await last.locator('.cw6-card-detail').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.detail-panel')).toBeVisible()
  await expect.poll(() => page.locator('.detail-portrait').evaluate(image => image.complete && image.naturalWidth > 0)).toBe(true)
  if (width <= 768) {
    await expect(page.locator('.gallery-wrap')).toBeHidden()
    await expect(cards.locator('img[src]')).toHaveCount(0)
  }
  await page.locator('.detail-close').click()
  if (width <= 768) await expect(last.locator('.cw6-card-detail')).toBeFocused()
  await expect(lastArt).toHaveAttribute('src', /.+/)
  expect(await storage(page)).toEqual(saved)
})
