import { test, expect, settle } from './fixtures.js'

test('desktop navigation closes with Escape and keeps focus and ARIA in sync', async ({ page, path }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(path('/'))
  await settle(page)
  const group = page.locator('.nav-group').first()
  const trigger = group.locator('.nav-link')
  const menu = group.locator('.nav-menu')
  await trigger.focus()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(menu).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await expect(menu).toBeHidden()
  await expect(trigger).toBeFocused()
  await page.mouse.move(0, 600)
  await trigger.evaluate(element => element.blur())
  await group.hover()
  await expect(menu).toBeVisible()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Escape')
  await expect(menu).toBeHidden()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})

test('home hero shades the copy on the correct reading side', async ({ page, path, locale }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto(path('/'))
  await settle(page)
  const shade = page.locator('.home-hero-shade')
  await expect(shade).toBeVisible()
  const transform = await shade.evaluate(element => getComputedStyle(element).transform)
  if (locale === 'ar') expect(transform).toMatch(/^matrix\(-1,/)
  else expect(transform).toBe('none')

  await page.setViewportSize({ width: 390, height: 844 })
  await expect(shade).toBeHidden()
  const copy = page.locator('.home-hero-content')
  await expect(copy.locator('h1')).toBeVisible()
  expect(await copy.evaluate(element => getComputedStyle(element).backgroundColor)).not.toBe('rgba(0, 0, 0, 0)')
})
