import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { readCharacters } from './seo/routes.mjs'

const root = fileURLToPath(new URL('../', import.meta.url))

// This projection contains counts only; the character and card datasets remain
// authoritative. Regenerate before both development and production builds.
export function deriveArchiveOverview(characters, cards) {
  const releases = new Map()
  for (const card of cards) {
    const time = card.publicTime ? card.publicTime * 1000 : 0
    if (!Number.isSafeInteger(time) || time < 0) throw new Error('Invalid CW6 publicTime')
    releases.set(time, (releases.get(time) || 0) + 1)
  }
  return {
    characterCount: characters.filter(character => character.country !== 'unknown').length,
    cardReleases: [...releases].sort(([a], [b]) => a - b),
  }
}

export function generateArchiveOverview() {
  const cards = JSON.parse(readFileSync(resolve(root, 'data/cw6_scene_cards.json'), 'utf8')).cards || []
  const metadata = deriveArchiveOverview(readCharacters(), cards)
  const output = resolve(root, 'src/generated/archive-overview.js')
  const content = '// Generated by scripts/generate_archive_overview.mjs. Do not edit.\nexport default ' + JSON.stringify(metadata) + '\n'
  mkdirSync(dirname(output), { recursive: true })
  let previous = ''
  try { previous = readFileSync(output, 'utf8') } catch { /* first generation */ }
  if (previous !== content) writeFileSync(output, content)
  console.log(`generate_archive_overview: ${metadata.characterCount} characters, ${cards.length} scheduled cards`)
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) generateArchiveOverview()
