import fs from 'node:fs'
import path from 'node:path'
import { createServer } from 'vite'
import {
  htmlOutputPath,
  legacyCharacterRoutes,
  renderRoutes,
} from './seo/routes.mjs'

const repoRoot = process.cwd()
const outputDir = path.join(repoRoot, 'dist')
const templatePath = path.join(outputDir, 'index.html')
const template = fs.readFileSync(templatePath, 'utf8')
const ogLocales = { en: 'en_US', ja: 'ja_JP', ar: 'ar_EG' }

const escapeHtml = (value) => String(value)
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')

function stripManagedHead(document) {
  const metaKeys = new Set([
    'description',
    'keywords',
    'robots',
    'og:type',
    'og:site_name',
    'og:locale',
    'og:locale:alternate',
    'og:title',
    'og:description',
    'og:url',
    'og:image',
    'og:image:type',
    'og:image:width',
    'og:image:height',
    'og:image:alt',
    'twitter:card',
    'twitter:title',
    'twitter:description',
    'twitter:image',
    'twitter:image:alt',
  ])
  return document
    .replace(/<title>[\s\S]*?<\/title>/gi, '')
    .replace(/<meta\b[^>]*>/gi, (tag) => {
      const key = /\b(?:name|property)=["']([^"']+)["']/i.exec(tag)?.[1]
      return key && metaKeys.has(key) ? '' : tag
    })
    .replace(/<link\b[^>]*>/gi, (tag) => {
      const rel = /\brel=["']([^"']+)["']/i.exec(tag)?.[1]
      return rel === 'canonical' || (rel === 'alternate' && /\bhreflang=/i.test(tag)) ? '' : tag
    })
    .replace(/<script\b[^>]*\bid=["']ranhq-schema["'][^>]*>[\s\S]*?<\/script>/gi, '')
}

function managedHead(seo) {
  const alternates = Object.entries(seo.alternates)
    .map(([language, href]) => `    <link rel="alternate" hreflang="${escapeHtml(language)}" href="${escapeHtml(href)}" />`)
    .join('\n')
  const alternateOgLocales = Object.entries(ogLocales)
    .filter(([code]) => code !== seo.locale)
    .map(([, value]) => `    <meta property="og:locale:alternate" content="${value}" />`)
    .join('\n')
  const schema = JSON.stringify(seo.structuredData).replaceAll('<', '\\u003c')
  return [
    '    <!-- RanHQ route metadata: generated by scripts/prerender.mjs -->',
    `    <title>${escapeHtml(seo.title)}</title>`,
    `    <meta name="description" content="${escapeHtml(seo.description)}" />`,
    `    <meta name="robots" content="${escapeHtml(seo.robots)}" />`,
    `    <link rel="canonical" href="${escapeHtml(seo.url)}" />`,
    alternates,
    '    <meta property="og:type" content="website" />',
    '    <meta property="og:site_name" content="RanHQ" />',
    `    <meta property="og:locale" content="${ogLocales[seo.locale]}" />`,
    alternateOgLocales,
    `    <meta property="og:title" content="${escapeHtml(seo.title)}" />`,
    `    <meta property="og:description" content="${escapeHtml(seo.description)}" />`,
    `    <meta property="og:url" content="${escapeHtml(seo.url)}" />`,
    `    <meta property="og:image" content="${escapeHtml(seo.image)}" />`,
    '    <meta property="og:image:type" content="image/jpeg" />',
    '    <meta property="og:image:width" content="1200" />',
    '    <meta property="og:image:height" content="630" />',
    `    <meta property="og:image:alt" content="${escapeHtml(seo.imageAlt)}" />`,
    '    <meta name="twitter:card" content="summary_large_image" />',
    `    <meta name="twitter:title" content="${escapeHtml(seo.title)}" />`,
    `    <meta name="twitter:description" content="${escapeHtml(seo.description)}" />`,
    `    <meta name="twitter:image" content="${escapeHtml(seo.image)}" />`,
    `    <meta name="twitter:image:alt" content="${escapeHtml(seo.imageAlt)}" />`,
    `    <script id="ranhq-schema" type="application/ld+json">${schema}</script>`,
  ].filter(Boolean).join('\n')
}

// The hero banner is the LCP element on Home and nowhere else. Left in the
// shared template it is fetched at high priority on all 900+ other documents,
// which Chrome reports as an unused preload.
function stripHeroPreload(document) {
  // The tag is authored across several lines, so walk <link ... > spans
  // rather than matching a single line.
  let out = document
  for (;;) {
    let cursor = 0
    let removed = false
    while (cursor < out.length) {
      const open = out.indexOf('<link', cursor)
      if (open === -1) break
      const close = out.indexOf('>', open)
      if (close === -1) break
      const tag = out.slice(open, close + 1)
      if (tag.includes('ranhq-home-banner') && tag.includes('rel="preload"')) {
        out = out.slice(0, open) + out.slice(close + 1)
        removed = true
        break
      }
      cursor = close + 1
    }
    if (!removed) return out
  }
}

function buildDocument(appHtml, seo) {
  const direction = seo.locale === 'ar' ? 'rtl' : 'ltr'
  const isHome = seo.canonicalPath === '/'
  let document = stripManagedHead(template)
  if (!isHome) document = stripHeroPreload(document)
  document = document.replace(/<html\b[^>]*>/i, `<html lang="${seo.locale}" dir="${direction}">`)
  document = document.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`)
  document = document.replace('</head>', `${managedHead(seo)}\n  </head>`)
  return document
}

function writeRoute(routePath, html) {
  const target = htmlOutputPath(outputDir, routePath)
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, html)
}

const vite = await createServer({
  root: repoRoot,
  appType: 'custom',
  logLevel: 'error',
  server: { middlewareMode: true },
})

try {
  const { render, seoForUrl } = await vite.ssrLoadModule('/src/entry-server.jsx')
  const routes = [...renderRoutes(), ...legacyCharacterRoutes()]
  for (let index = 0; index < routes.length; index += 1) {
    const route = routes[index]
    const appHtml = await render(route.path)
    const seo = seoForUrl(route.path)
    writeRoute(route.path, buildDocument(appHtml, seo))
    if ((index + 1) % 100 === 0 || index === routes.length - 1) {
      console.log(`prerender: ${index + 1}/${routes.length}`)
    }
  }

  const notFoundHtml = await render('/404')
  writeRoute('/404', buildDocument(notFoundHtml, seoForUrl('/404')))
  console.log(`prerender: wrote ${routes.length} route documents plus 404.html`)
} finally {
  await vite.close()
}
